# SPDX-License-Identifier: MIT
# Taskfile.yml - Infrastructure Setup Automation
# ------------------------------------------------------------
# This Taskfile automates the setup and deployment of the
# development environment, including installing Pulumi,
# Minikube, and Kubernetes CLI tools.
#
# Usage:
#   - task setup        # Installs dependencies
#   - task deploy-cluster # Starts a local Kubernetes cluster
# ------------------------------------------------------------

version: '3'

tasks:
  setup:
    desc: "Installs required dependencies (Pulumi, Kubernetes CLI, etc.)"
    cmds:
      - task: install:asdf
      - task: install:pnpm
      - task: install:pulumi
      - task: login:pulumi
      - task: install:pulumi-packages
      - task: install:kubernetes
    silent: false

  install:pulumi:
    desc: "Installs Pulumi CLI"
    cmds:
      - bash ./scripts/install_pulumi.sh

  install:pulumi-packages:
    desc: "Installs Pulumi dependencies"
    cmds:
      - cd infrastructure && pnpm install --frozen-lockfile

  install:kubernetes:
    desc: "Installs Minikube & kubectl"
    cmds:
      - bash ./scripts/install_kubernetes.sh

  install:asdf:
    desc: "Installs asdf version manager"
    cmds:
      - bash ./scripts/install_asdf.sh

  install:pnpm:
    desc: "Installs pnpm package manager"
    cmds:
      - bash ./scripts/install_pnpm.sh

  login:pulumi:
    desc: "Logs into Pulumi using local backend"
    cmds:
      - pulumi login --local

  init:pulumi-stack:
    desc: "Ensures the Pulumi stack exists before deployment"
    cmds:
      - cd infrastructure && pulumi stack select dev || pulumi stack init dev

  deploy-cluster:
    desc: "Deploys the Kubernetes cluster with Pulumi"
    deps: [init:pulumi-stack]
    cmds:
      - cd infrastructure && pulumi up --yes
