# SPDX-License-Identifier: MIT
# Taskfile.yml - Infrastructure Setup Automation
# ------------------------------------------------------------
# This Taskfile automates the setup and deployment of the
# development environment, including installing Pulumi,
# Minikube, and Kubernetes CLI tools.
#
# Usage:
#   - task setup        # Installs dependencies
#   - task deploy-cluster # Starts a local Kubernetes cluster
# ------------------------------------------------------------

version: '3'

tasks:
  setup:
    desc: "Installs required dependencies (Pulumi, Kubernetes CLI, etc.)"
    cmds:
      - task: install:pulumi
    silent: false

  install:pulumi:
    desc: "Installs Pulumi CLI"
    cmds:
      - |
        if ! command -v pulumi &> /dev/null; then
          echo "Installing Pulumi..."
          curl --fail --silent --show-error --location https://get.pulumi.com | sh -s -- --install-root "${PULUMI_HOME}" --no-edit-path
        else
          echo "✅ Pulumi is already installed."
        fi
      - pulumi version

  install:kubernetes:
    desc: "Installs Minikube & kubectl"
    cmds:
      - |
        if ! command -v minikube &> /dev/null; then
          echo "Installing Minikube..."
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
        else
          echo "✅ Minikube is already installed."
        fi
      - minikube version
      - |
        if ! command -v kubectl &> /dev/null; then
          echo "Installing kubectl..."
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/kubectl
        else
          echo "✅ kubectl is already installed."
        fi
      - kubectl version --client

  deploy-cluster:
    desc: "Deploys a local Kubernetes cluster"
    cmds:
      - echo "🚀 Starting Minikube..."
      - minikube start
      - echo "✅ Kubernetes cluster is running!"
