services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    # command: sleep infinity
    environment:
      - PULUMI_CONFIG_PASSPHRASE=
    ports:
      - "30080:30080"
      - "30081:30081"
